### ISSUE TITLE
tempfile related problems on MXE windows build

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1182]
from octave.discourse.group:

```
A couple of tests are failing in the CI with the nightly builds for Windows:
[freshly brewed Octave · gnu-octave/octave-buildbot@43f176e (github.com)](https://github.com/gnu-octave/octave-buildbot/runs/7238133932?check_suite_focus=true#step:13:15477)

Some of the errors seem to emit things like this:

  python: can't open file '/mingw64/share/octave/packages/symbolic-3.0.0/D:\a\_temp\oct-EEh6sa_octsympytmp.py': [Errno 2] No such file or directory

It looks like this could be two absolute paths that are concatenated. That is probably ok for most paths on a Linux file system. But it is failing on Windows.

Edit: That’s still with SymPy 1.5 in case that should matter.
```

**update**I have trouble finding things later on discourse, not sure why, so I don't waste 5 mins in the future, here's the link https://octave.discourse.group/t/symbolic-3-0-0-released/2975/5

**Comment by cbm755** [comment]
@alexvong1995 can you look into this?

**Comment by alexvong1995** [comment]
Could this be a `tempname()` problem? How should we reproduce it?

**Comment by cbm755** [comment]
I'm not sure :(  I did run our test suite on a Windows machine (Octave 5.2.0) before releasing and I did not see this.  Perhaps its something about cross-compiling?  But I agree we're just using what `tempname()` gives us here, which is apparently

```
/mingw64/share/octave/packages/symbolic-3.0.0/D:\a\_temp\oct-EEh6sa_
```
That "D:" in the middle of a path seems invalid on Windows to me...  @mmuetzel is it possible this is an upstream Octave / MXE builder problem...

**Comment by cbm755** [comment]
The other errors in that log look like:
```
   Traceback (most recent call last):
    File "<string>", line 1, in <module>
  FileNotFoundError: [Errno 2] No such file or directory: 'D:\x07\\octave-buildbot\\octave-buildbot\\octave-2022-07-07-00-12-w64\\mingw64\\share\\octave\\packages\\symbolic-3.0.0\\private\\python_header.py'
```
Note the very different paths which look more reasonably and don't have a mixture of slashes and backslashes... unlike what tempname is giving us: `/mingw64/share/octave/packages/symbolic-3.0.0/D:\a\_temp\oct-EEh6sa_`

**Comment by cbm755** [comment]
Hold on, this construction is maybe suspicious to me:
```
tmpfilename = [tempname() '_octsympytmp.py'];
```
Is there some problem about backslashes etc when you concatenate strings?  Sounds familiar to me...

**Comment by mmuetzel** [comment]
Hmm... It looks like the Python that is included in Octave for Windows is for Cygwin. But the Octave program itself is for native MinGW.
By the looks of it, that Cygwin Python has issues when it gets passed a native Windows path. It expects a Cygwin path instead.

I don't know why this is a Cygwin Python and not a MinGW Python.
@lostbard: Would it be possible to include a MinGW Python in MXE Octave? Or do you have an idea how that could be solved otherwise?

**Comment by cbm755** [comment]
For the record, I think the previous behaviour of Symbolic here was to great a temp file in the current working directory.  Which is rude (see #1140).  But that is presumably why previous versions did not hit this issue.

**Comment by lostbard** [comment]
@mmuetzel should already using msys2 python

in mxe: src/msys2-python.mk

**Comment by mmuetzel** [comment]
IIUC, that uses (an older version of) this package:
https://packages.msys2.org/base/python

The un-prefixed MSYS2 packages are basically Cygwin applications. (IIUC, the MSYS2 target is just a rechristened Cygwin with very minor modifications.) Those applications aren't really native to Windows. But they expect a Linux-like platform that is provided by Cygwin/MSYS2. 

The native Windows applications are prefixed with `mingw-w64` in MSYS2, and are distributed for different “environments" (e.g. MINGW32 or MINGW64). That would be one of these packages:
https://packages.msys2.org/base/mingw-w64-python

It looks like the Cygwin Python expects UNIX paths and cannot correctly handle the Windows path that it gets. That seems to be the cause for the issue here.

I don't know if it would be possible to just use the native Python from MSYS2 (dependency hell). I also don't know how hard it would be to cross-build a native Windows Python in MXE Octave.
But maybe there is also another solution I can't think of currently.
Do you have an idea how to solve this?

**Comment by alexvong1995** [comment]
We can use the `cygpath` program to convert windows path to cygwin path. `cygpath` should be provided by cygwin https://cygwin.com/cygwin-ug-net/cygpath.html

**Comment by lostbard** [comment]
@mmuetzel ok now im with you

It should be possible, but yeah - then requires getting all the dependancies correct.

Currently, https://packages.msys2.org/package/mingw-w64-x86_64-python lists dependancies as:
[mingw-w64-x86_64-bzip2](https://packages.msys2.org/package/mingw-w64-x86_64-bzip2)
[mingw-w64-x86_64-expat](https://packages.msys2.org/package/mingw-w64-x86_64-expat)
[mingw-w64-x86_64-gcc-libs](https://packages.msys2.org/package/mingw-w64-x86_64-gcc-libs)
[mingw-w64-x86_64-libffi](https://packages.msys2.org/package/mingw-w64-x86_64-libffi)
[mingw-w64-x86_64-mpdecimal](https://packages.msys2.org/package/mingw-w64-x86_64-mpdecimal)
[mingw-w64-x86_64-ncurses](https://packages.msys2.org/package/mingw-w64-x86_64-ncurses)
[mingw-w64-x86_64-openssl](https://packages.msys2.org/package/mingw-w64-x86_64-openssl)
[mingw-w64-x86_64-sqlite3](https://packages.msys2.org/package/mingw-w64-x86_64-sqlite3)
[mingw-w64-x86_64-tcl](https://packages.msys2.org/package/mingw-w64-x86_64-tcl)
[mingw-w64-x86_64-tk](https://packages.msys2.org/package/mingw-w64-x86_64-tk)
[mingw-w64-x86_64-tzdata](https://packages.msys2.org/package/mingw-w64-x86_64-tzdata)
[mingw-w64-x86_64-xz](https://packages.msys2.org/package/mingw-w64-x86_64-xz)
[mingw-w64-x86_64-zlib](https://packages.msys2.org/package/mingw-w64-x86_64-zlib)

So would need them installed. 

Possibly though, if we look at all the msys2 packages already installed, some may have mingw-64 equivalents and could also be used, perhaps allowing us to use more of them and less msys ones.

As  a try of the mingw64 python, you could install it in octave-mxe after octave is installed via bash shell from the installed octave since there is enough msys2 utilities available in the install to do so:

# update database
pacman -Sy
# install python
pacman -S mingw-w64-x86_64-python


Im not sure if it will break anything else when it installs the dependancies, but worth a try perhaps

**Comment by lostbard** [comment]
actually gave it a try and it did conflict and not install so would need --no-deps to see if will work, or force it to install and overwrite existing files

**Comment by lostbard** [comment]
There is also a new msys python - that would possibly handle names better?

**Comment by alexvong1995** [comment]
Regardless of which flavour of python is shipped with octave in windows, I think we still need code to check if the python we found accepts native path or cygwin posix path, as users can decide which python to use by specifying the `PYTHON` environment variable.

After that, we can use `cygpath` https://cygwin.com/cygwin-ug-net/cygpath.html to do path conversion if required.

**Comment by mmuetzel** [comment]
Unfortunately, using `cygpath` wouldn't work in this particular case:
```
>> tmpfile = tempname()
tmpfile = C:\Users\Markus\AppData\Local\Temp\oct-rZDdea
>> system (['cygpath -u ', tmpfile])
/tmp/oct-rZDdea
ans = 0
```

For some reason, a path that points to a file at the native temporary directory seems to get translated to a path for a file in the MSYS2 temporary directory. Those are different locations in general. The latter has the following "Windows native" path for me: `C:\Program Files\GNU Octave\Octave-7.1.0\tmp` (or wherever Octave was installed). 

The "proper" Unix-path that would correspond to the original file in the location above would be `/C/Users/Markus/AppData/Local/Temp/oct-rZDdea`. So, the file that `cygpath` returns wouldn't exist.

I'm not sure if this is a bug in `cygpath` or if this translation is done for some other compatibility(?) reason.

Even if there was an option to get the path translation that we'd need here, it would probably be hard to reliably detect automatically if the used Python is a Cygwin or a native Windows application.

**Comment by mmuetzel** [comment]
> There is also a new msys python - that would possibly handle names better?

I wouldn't expect that it would behave much differently when it comes to paths.

**Comment by alexvong1995** [comment]
IIUC we can check if python is cygwin python using `python3 -c "import platform; platform.system()"` as mentioned in https://stackoverflow.com/questions/42820914/check-if-running-in-windows-command-prompt-vs-cygwin-python

If we are indeed using cygwin python, perhaps we can just use cygwin mktemp to create temporary file, e.g.

```
[fin, fout, pid] = popen2 ('mktemp');

assert (fclose (fin) == 0);

tmpfilename = fgetl (fout)
assert (fgetl (fout) == -1);
assert (fclose (fout) == 0);

assert (waitpid (pid) >= 0);
```

Or we can get the path translation working. Does `python3 "/tmp/oct-rZDdea"` output nothing w/o error when using cygwin python?

**Comment by mmuetzel** [comment]
Maybe I was jumping to wrong conclusions regarding the path translation.
For a test, I made the following change to `python_ipc_system.m` (in Octave for Windows from MXE Octave):
``` diff
     info.prelines = info.prelines + 2;
     fputs(fd, bigs);
     fclose(fd);
-    [status, out] = system ([pyexec ' ' tmpfilename]);
+    [~, tmpfilename_u] = system (['cygpath -u ' tmpfilename]);
+    [status, out] = system ([pyexec ' ' tmpfilename_u]);
   end
 
   info.raw = out;
 
```

With it, I see the following:
```
>> sympref('ipc', 'systmpfile');

>> syms x

>>
```
So, that seems to be working (contrary to what I thought before). 🎉

If there is a way to reliably detect if Python is a Cygwin/MSYS2 or a native Windows application and you don't mind "polluting" your code with special cases, that might be workable solution.
But it might need modifications in more places. With that change above applied, I still see failing test(s):
```
>> pkg load symbolic

>> test sympref

Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Octave\test\\octave-2022-07-07-09-04-w64 sympy-1.10.1\\octave-2022-07-07-09-04-w64\\mingw64\\share\\octave\\packages\\symbolic-3.0.0\\private\\python_header.py'
status = 1
out =
ind = [](0x0)
***** test
 % system should work on all system, but just runs sysoneline on windows
 sympref('ipc', 'system');
 syms x
!!!!! test failed
sysoneline ipc: system() call failed!
shared variables     sympref_orig =

      scalar structure containing the fields:

        ipc = default
        display = ascii
        digits = 32
        quiet = 0

>>
```



> IIUC we can check if python is cygwin python using `python3 -c "import platform; platform.system()"`

This is what I see for this command in the same Octave:
```
>> system ('python3 -c "import platform; platform.system()"')
ans = 0
>> [a, b] = system ('python3 -c "import platform; platform.system()"')
a = 0
b =
>> [a, b] = system ('python -c "import platform; platform.system()"')
a = 0
b =
```
Am I doing something wrong?

**Comment by mmuetzel** [comment]
Fwiw, with the Octave in MSYS2 (and native Python), there are no unexpected failing tests:
```
>> pkg test symbolic
[...]
Summary:

  PASS                             2402
  FAIL                                0
  XFAIL (expected failure)           31
```

**Comment by cbm755** [comment]
>  and you don't mind "polluting" your code with special cases, that might be a workable solution.

I've somewhat lost the thread (or "path"? ;-) heh) here but no objection in principle: we have lots of "special cases" already...

**Comment by mmuetzel** [comment]
If I understand the current conclusions correctly, we could convert the paths that are passed to Python to make this work.
IIUC, that would require these steps:
* Identify where paths are passed as command line arguments to the Python executable.
* Check whether Python is native or Cygwin on Windows. For this, we could probably use a combination of `ispc` and comparing the second output of `system('python3 -c "import os; print(os.name)"')` to `posix`. It might make sense to keep the result in a persisten variable to avoid spawning new Python processes if possible.
* If both compare true, convert the path with `cygpath -u`.
* Pass the converted path to the Python executable.

**Comment by mmuetzel** [comment]
> There's yet another way to do it (potentially simpler?). We can check if 'python3 -c "import os.path; print(os.path.sep)"' outputs the same separator as 'octave --eval "filesep()"'. If 'python3 -c "import os.path; print(os.path.sep)"' outputs '/' but 'octave --eval "filesep()"' outputs '\', we know we are using cygwin/msys2 python.

Not sure if this will work reliably in the future. Both `\` and `/` are valid file separators in Windows paths. Maybe Python or Octave might decide to use `/` also on Windows at some point in the future.

**Comment by cbm755** [comment]
I've kind lost the thread here: are we trying to fix `tempname` upstream or are we trying to workaround this in Symbolic?

**Comment by cbm755** [comment]
I think this can be closed.
