### ISSUE TITLE
Appropriate to ship octsympy_doctest.m?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#238]
@oheim said:

    One comment on the octsympy_doctest.m: Do you really want to release it as a public function?
    Why would a user run the doctest?

This is a good point.  Where do you put such a thing in `interval` pkg?

**Comment by oheim** [comment]
http://sourceforge.net/p/octave/interval/ci/1fcf7ef59ec306d056fd725428cc88de98203fdd/tree/Makefile#l210

It's in my maintainer's Makefile. The list of functions, classes and texinfo files to be tested is generated with the help of some ls/find magic.

Currently there is some boilerplate code for adding paths for the doctest functions to work, which is going to vanish as soon as I can install doctest as a package in Octave.

**Comment by oheim** [comment]
Btw, I have thought about the following: You could write a function in the doctest package, which could be used to check any loaded package, e. g. with “doctest_pkg('octsympy')”, which in turn scans any functions, classes and the doc folder of that installed package.

However, this is not a good idea, because—as a maintainer—it's easier for me to check the source files directly (see Makefile) and not having to install the package first in Octave (which takes additional time after each revision of the sources).

**Comment by cbm755** [comment]
@oheim Do you have a central version of the maintainers makefile?    If I adopt that, I will need to make some changes to support git, and would rather not maintain a fork of it!

**Comment by oheim** [comment]
@cbm755, you could use the Makefile from the interval package and drop all the unneeded stuff (generated tests, image conversion for the manual, generating the NEWS and COPYING from texinfo sources, generating the package documentation, …). The only mercurial related stuff should be in this rule:
```
$(RELEASE_TARBALL): .hg/dirstate
	@echo "Creating package release ..."
	@mkdir -p "$(BUILD_DIR)"
	@hg archive --exclude ".hg*" --exclude "Makefile" --exclude "*.sh" "$@"
```
The dirstate file is used to determine, whether the mercurial version has changed.

We do not have a central version of that file, because every package probably need some variations. I you get stuck adopting it, I would be glad to help.
