### ISSUE TITLE
2 tests broken octsympy/octave

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#294]
Hi, 
Some test broken octsympy:

in test_bugs.tst
```
%!xtest
%! % symbolic matrix, subs in for size, Issue #160
%! syms n m integer
%! A = sym('A', [n m]);
%! B = subs(A, [n m], [5 6]);
%! assert (isa (B, 'sym'))
%! assert (isequal (size (B), [5 6]))
%! % FIXME: not same as an freshly created 5 x 6.
%! C = sym('B', [5 6]);
%! (isequal(B, C))
%! % FIXME: e.g., cannot add to it
%! B = B + 1
%! assert (isa (B, 'sym'))
```
line:
```
%! (isequal(B, C))
```

in int.m:
```
%!test
%! % NonElementaryIntegral bug
%! % https://savannah.gnu.org/bugs/index.php?46831
%! f = int(exp(exp(x)));
%! f = f + 2;
%! g = diff(f);
%! assert (isequal (g, exp(exp(x))))
```
line:
```
%! f = f + 2;
```

when this test runs then the nexts test fails for broke octsympy...
an option should be commit or fix it.

**Comment by latot** [comment]
forgive it, for some reason my octave don't is working good

**Comment by latot** [comment]
Well, now this is more weird, if i run this two test individually works, but is i run it from octsympy_tests, brokes octave

**Comment by cbm755** [comment]
Yes, this is another case where eval(srepr())` is not the identity map in SymPy.  I can fix this...

This tends to leave the communication layer in such a broken state: I think its because the error occurs during *variable import* (`python_copy_vars_to.m`) rather than during the code execution itself.
