### ISSUE TITLE
big numbers

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#361]
Hi, well othe problem in octave affecting here, ex:

```
sym(100000000000000000000000)
ans = (sym) 99999999999999991611392
```

two options of temporary solve:

1)use exp
```
sym(10)^23
```

2) use ""
```
sym("100000000000000000000000")
```

**Comment by cbm755** [comment]
This is because `100000000000000000000000` is a double in Octave.

(`sym(10^23)` doesn't help but `sym(10)^23` does, which is probably what you meant).

Impossible to "fix" this.  But we could improve:

1.  could probably document better: basically `sym(10)` is only "safe" for small integers for some definition of small.  

2.  could output a warning, like the `rat` warning for `sym(2/3)`.  This should happen for double input when the double is larger than `10^16` (double check this is correct).

E.g.,
````
>> sym(1000000000000001)
ans = (sym) 1000000000000001
>> sym(10000000000000001)
ans = (sym) 10000000000000000
````

**Comment by cbm755** [comment]
Do you want to try this or shall I?

**Comment by latot** [comment]
can you plis?
