### ISSUE TITLE
Windows: python installed in dir with spaces ("c:\Program Files") breaks configure

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#371]
I had some time on a Windows system so I tried installing Octave and Symbolic.

  * System was Windows 10.
  * I tried installing Python 3.5 using these options (see screenshots)
      - [x] Add Python 3.5 to Path 
      - [x] Install for all users
      - install location: "C:\Program Files\Python35"

![capture](https://cloud.githubusercontent.com/assets/818622/13557644/b7cf29c6-e3a9-11e5-9ab7-f4740f504033.PNG)

![capture2](https://cloud.githubusercontent.com/assets/818622/13557645/c2fe1f78-e3a9-11e5-9fbd-05f14f6357d1.PNG)

Now, note installing Symbolic doesn't work:

![capture3](https://cloud.githubusercontent.com/assets/818622/13557646/c646ecf0-e3a9-11e5-9e1f-f5d650d2a4cf.PNG)

Transcripting from the screenshot:
````
./configure: line 1762: test: /c/Program: binary operator expected
./configure: line 1767: test: /c/Program: binary operator expected
````
(Its possible I had not yet installed sympy but even so those messages don't look right.)

It looks to me like the space in "Program Files" causes trouble.

**Comment by cbm755** [comment]
For above, the system was 64 bit so I installed python using `python-3.5.1-amd64-webinstall.exe`.

I also tried again with 32bit Python (`python-3.5.1-webinstall.exe`) which I think installed in `C:\Program Files (x86)\Python35` or something like that.  It also breaks with an even worse error:

![capture_python_with_spaces_maybe](https://cloud.githubusercontent.com/assets/818622/13557716/949bd78c-e3aa-11e5-9243-9477f3bb9c30.PNG)

**Comment by cbm755** [comment]
Notice also the `:` in `C:\` is missing in places.

**Comment by cbm755** [comment]
So far its work when **I do _not_ check the box "install for all users"**.  Then it seems to install in `c:\users\<username>\Python35` or something like that.  And AFAICT, things work correctly.

**Comment by cbm755** [comment]
@genuinelucifer if you have a moment, are you able to test/confirm any of this?

**Comment by genuinelucifer** [comment]
Yup. I also installed python 3.4 in ```C:/Program Files (x86)/Python34``` and got the following error:
```
>> pkg install -forge symbolic
./configure: line 1762: test: too many arguments
./configure: line 1767: test: too many arguments
basename: extra operand `(x86)/Python34/python'
Try `basename --help' for more information.
configure: error: failed to find required module sympy
checking for sort... /usr/bin/sort
checking for GNU coreutils... yes
checking for python... /c/Program Files (x86)/Python34/python
checking  module: sympy... no

pkg: error running the configure script for symbolic.
error: called from 'configure_make' in file E:\octave-4.0.0\share\octave\4.0.0\m\pkg\private\configure_ma
ke.m near line 79, column 9
```
.
A solution that comes to my mind and a probable cause of this error.
When passing a path as an argument to a program, I have developed a habit of always using double quotes around it because many times I have found such error as the 2 words are treated as separate arguments. So, even if the path doesn't have a space, passing it with double quotes is probably the best idea.

**Comment by cbm755** [comment]
Yeah that sounds good.  Maybe on line 18 of `configure.ac`

`if test -z $PYTHON; then`

to

`if test -z "$PYTHON"; then`

That seems to do no harm on GNU/Linux:
````
$ grep configure.ac -e test
if test $? -ne 0;
if test -z "$PYTHON"; then
if test $? -eq 0; then
$ ./bootstrap 
./bootstrap: done.  Now you can run './configure'.
$ ./configure 
checking for sort... /usr/bin/sort
checking for GNU coreutils... yes
checking for python... /usr/local/bin/python
checking python module: sympy... yes
checking for SymPy version... 0.7.6
checking for gawk... gawk
$
````

If you're able to, can you test on Windows?  Otherwise, I will next time I have access to a Windows machine...

**Comment by genuinelucifer** [comment]
Sorry but I can't find ```configure.ac```!

**Comment by genuinelucifer** [comment]
Oops. I was looking in the windows bundle. Finally found the file. Will have to switch to linux to test. I'll test and post the results tomorrow.

**Comment by genuinelucifer** [comment]
@cbm755 When i run the commands that you ran.
I'm getting:
```
~/octsympy/src$ ./bootstrap 
./bootstrap: 3: ./bootstrap: aclocal: not found
./bootstrap: 4: ./bootstrap: autoconf: not found
./bootstrap: done.  Now you can run './configure'.
~/octsympy/src$ ./configure
bash: ./configure: No such file or directory
```
Then i did:
``` sudo chmod +x configure.ac ```
And ran configure.ac but getting errors.
.
.
I couldn't find a way to run these on windows that's why I switched to linux. I intend to build the windows zip file from linux and then install that zip in octave on windows to test. Am I  going in the right direction?

**Comment by cbm755** [comment]
I'm not expert on autoconf, but `bootstrap.sh` builds `configure` from `configure.ac`

Looks like you're missing some basic dev tools on your GNU/Linux box, namely `aclocal` and `autoconf`.

**Comment by genuinelucifer** [comment]
Finally I could successfully run the commands on linux.
Although i had to change ```aclocal``` in bootstrap to ```aclocal -I m4 --install``` to make it work.
.
Now, if I run ```make_windows_package.sh``` It is downloading a the complete repo from git and then bundling it. Does it make sure to include my recent changes? How do I make the zip package such that my local changes are preserved?

**Comment by genuinelucifer** [comment]
After using the quotes and making the windows zip. When I installed it in octave I didn't get the error lines
```basename: extra operand `(x86)/Python34/python'
Try `basename --help' for more information.```
But rest of the error lines were there. Probably due to my own zip file instead of installing from forge. Or maybe that the python path problem got solved but some other problem (due to path of some other tool) still remains.

**Comment by cbm755** [comment]
Ok, you can send me a PR for just the quotes around `$PYTHON` if you want: get that merged it first...

**Comment by genuinelucifer** [comment]
Just did. :)

**Comment by cbm755** [comment]
A potential problem is that autoconf stuff has lots of macro files (from... somewhere...).  Perhaps one of those is uptight about spaces in filename.  This feels so "1995" :(

Our use of autoconf is minimal: it basically just checks if Python and SymPy are installed (see #196 for details).

**Comment by genuinelucifer** [comment]
I was looking into the scripts for probable causes. I think I might have found a few more possible tweaks that might help. Meanwhile, Mid semester exams have started in my college, so I am unable to work on it for the next 5-6 days.
I'll definitely try to come with something after 17th. :)

**Comment by genuinelucifer** [comment]
@cbm755 I have found this issue in many other softwares on windows (ex: lex, yacc and many others on windows).. And all they suggest is to use a directory without spaces. Even python take default directory as "C:/pythonxy" (without spaces)... I guess, a proper note at this point (till a final solution is reached) asking the user (in some sort of faq) to install python in a directory without spaces should be made?!

**Comment by cbm755** [comment]
most of those tools come with Octave itself.  Do you still get errors/warnings with Symbolic 2.3.0?  Can you copy paste them here?

**Comment by genuinelucifer** [comment]
It seems that the packaged ```configure``` file has errors. When I used the original ```symbolic-2.3.0.zip``` (downloaded from github) then I get the following error on issuing ```pkg install symbolic-2.3.0.zip```
```
./configure: line 1767: test: too many arguments
basename: extra operand `(x86)/Python34/python'
Try `basename --help' for more information.
configure: error: failed to find required module sympy
checking for sort... /usr/bin/sort
checking for GNU coreutils... yes
checking for python... /c/Program Files (x86)/Python34/python
checking  module: sympy... no

pkg: error running the configure script for symbolic.
error: called from 'configure_make' in file E:\octave-4.0.0\share\octave\4.0.0\m\pkg\private\configure_ma
ke.m near line 79, column 9
```

But then I unzipped the zip. And deleted the file ```configure``` (NOT configure.ac) and zipped it back. Now If i issue the commands it gets succesfully installed!!
```
>> pkg install symbolic-2.3.0.zip
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>> pkg load symbolic
>> syms
Symbolic variables in current scope:
>> syms x
OctSymPy v2.3.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected Windows: using "winwrapy.bat" to workaround Octave bug #43036
Some output from the Python subprocess (pid 4032) might appear next.

Closing the Python pipe...
error: Python exception: ImportError: No module named 'sympy'
    occurred in python_header import block
error: called from
    python_cmd at line 178 column 5
    sym at line 364 column 5
    syms at line 158 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 158 column 9
```

There error only states that sympy is not found (I haven't installed sympy on windows)... So, I guess if the pre-built configure file is removed from the zip then it works. And octave builds the configure file anyway (using some local bash sort of thing)...

**Comment by cbm755** [comment]
Before I think to carefully about this, did you `./bootstrap` before making the `.zip` file?  Maybe you included an old `./configure`?

**Comment by genuinelucifer** [comment]
Nope. I didn't do anything.
.
First, i just downloaded the zip and used it. Error.
.
Then simple unzip. Delete the file. Zip.
And try. Success.

**Comment by cbm755** [comment]
Ok, sorry I was thinking about making a .zip file from source (where ./bootstrap must be run as part of preparing the package)...

> And octave builds the configure file anyway (using some local bash sort of thing)...

Does it?  It looks like it simply doesn't run `./configure` when that file does not exist.

**Comment by genuinelucifer** [comment]
> Does it? It looks like it simply doesn't
> run ./configure when that file does not exist.

Oh sorry. I just read somewhere that octave has a mini bash with it. So i
had a view it might be for configuring all the packages. Why else? But now
that you mention it. Yes i didn't see any output listing that python is
found but sympy is not while installation.
Probably the other issue that you opened about dropping autoconf would
solve it all together.

**Comment by genuinelucifer** [comment]
@cbm755 You can close this issue now. It seems to have been resolved with the double quotes only (or by some later changes)..

Actually my path had some other bin directories and probably caused problems... when I did `getenv("PATH")` in octave I got the it had 2 parts.. First there were variables from my window's PATH and then there were some more directories. I just swapped the first part with the second in path and used `setenv` so that octave directories came before any directory from window's PATH... And tested with both the `.tar.gz` file on releases and using `-forge`.  
  
For the later I had to do `clear all` and then load symbolic again for it to work... (might be the same problem (i have faced sometimes) which fails to recognize the scripts in `inst/private`  on linux.  
  
In my view both errors are probably octave bugs.  
* Octave should append windows' PATH to the directories it requires in PATH and not the reverse (to allow higher precedence to executables that come with octave).  
* How does `clear all` fix some path related things?  
  
I installed python in `C:\Program Files (x86)\Python34` and then installed sympy and mpmath in it to work. Then here is the output of the commands in octave:  
```octave
>> pkg install symbolic-2.4.0.tar.gz
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>> pkg load symbolic
>> syms x
OctSymPy v2.4.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Using winwrapy.bat workaround for bug #43036 (Octave <= 4.0.2, on Windows)
Some output from the Python subprocess (pid 6568) might appear next.

OctSymPy: Communication established.  SymPy v1.0.
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
>> y = x^3
y = (sym)

   3
  x
>> pkg unload symbolic
>> pkg uninstall symbolic
>> pkg install -forge symbolic
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>> pkg load symbolic
>> syms x
error: 'python_ipc_popen2' undefined near line 57 column 15
error: called from
    python_ipc_driver at line 57 column 13
    python_cmd at line 166 column 9
    sym at line 365 column 5
    syms at line 162 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 162 column 9
>> clear all
>> pkg load symbolic
>> syms x
OctSymPy v2.4.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Using winwrapy.bat workaround for bug #43036 (Octave <= 4.0.2, on Windows)
Some output from the Python subprocess (pid 1416) might appear next.

OctSymPy: Communication established.  SymPy v1.0.
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
>> y = sin(x)
y = (sym) sin(x)
```

**Comment by cbm755** [comment]
The "clear all" thing is about classes and their private fcns.  I've never been too worried about it as it doesn't effect users (just developers).

Re: Path: I'm not sure I understand.  Pasting examples of the output to the various commands might help, especially if you plan to file an upstream bug (sounds like you should).

Before I close this, can you confirm that it works when both:
1. Python installed to a path with spaces
2. Octave installed to a path with spaces
Thanks!

**Comment by genuinelucifer** [comment]
> The "clear all" thing is about classes and their private fcns. I've never been too worried about it as it
> doesn't effect users (just developers).  

Oh ok. But since it sometimes doesn't work for me makes me wonder if might even be happening to general users...  
  
> Path: I'm not sure I understand. Pasting examples of the output to the various commands might
> help, especially if you plan to file an upstream bug (sounds like you should).

Actually, if I run `octave-cli.exe` or `octave-gui.exe` from `<octave-dir>/bin/` then if I run `getenv("PATH")` I see that it has the following pattern: `<windows' PATH exactly as I can check on "My computer">;<many octave directories>;` and since my windows' PATH has `bin` directories of git, MSBuild and many other softwares I get weird errors. Sometimes it's about `sort` is not gnu sort. Sometimes `expr.exe` crashes... But If I do `setenv("PATH", modified_path)` then every error is resolved, where modified_path is `<many octave directories>;<windows' PATH exactly as I can check on "My computer">;`!   
Also, I found one more thing. If I run `<octave-dir>/octave.bat` then I get the PATH slightly modified such that it has one more `<octave-dir>/bin` in front of the regular result from `getenv("PATH")`!!
But if I run octave from either of the 2 executables (cli/gui) from `<octave-dir>/bin` then that extra path to octave's bin is not there in the start.  
  
To sumarise, I can build without changing anything if I run `<octave-dir>/octave.bat` but not if I run `<octave-dir>/bin/octave-cli.exe` or `<octave-dir>/bin/octave-gui.exe`!  
  
> Before I close this, can you confirm that it works when both

I just tried and it worked! I moved octave to `e:\Octave v4\<octave-dir>`... Also python was in `C:\Program Files (x86)\<python-dir>`... :)

**Comment by mtmiller** [comment]
>  Also, I found one more thing. If I run <octave-dir>/octave.bat then I get the PATH slightly modified such that it has one more <octave-dir>/bin in front of the regular result from getenv("PATH")!!
But if I run octave from either of the 2 executables (cli/gui) from <octave-dir>/bin then that extra path to octave's bin is not there in the start. 

That's correct, the bat file prepends Octave's bin directory to the `PATH`.

**Comment by genuinelucifer** [comment]
> That's correct, the bat file prepends Octave's bin directory to the PATH.

So, shouldn't octave-cli.exe and octave-gui.exe do the same? Because without that bin 'pre'-pended to PATH, I cannot install any packages (more appropriately, run configure)...

**Comment by mtmiller** [comment]
> So, shouldn't octave-cli.exe and octave-gui.exe do the same? Because without that bin 'pre'-pended to PATH, I cannot install any packages (more appropriately, run configure)...

We can discuss this somewhere else if you want, this is probably off topic for this issue, which now seems resolved.

But no, those executables should not change `PATH`, what you are seeing is the expected behavior. Setting environment variables like `PATH` is precisely the point of the bat file.

**Comment by genuinelucifer** [comment]
> We can discuss this somewhere else if you want, this is probably off topic for this issue, which now seems resolved.

Sure, I sent a mail to the list just a couple of minutes ago...

**Comment by cbm755** [comment]
Closing
