### ISSUE TITLE
drop configure script in favour of run-time checks

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#413]
I'm considering dumping all the autoconf stuff from Symbolic: we have
nothing to compile, all its used for is checking that Python and SymPy
are installed.  And it just seems to get in the way on Windows (#371) and
(apparently now) MacOS (#412).

@genuinelucifer 

@carandraug you added this originally and it certainly seemed like a good idea on GNU/Linux.  But now I'm not so sure...  Thoughts?

**Comment by cbm755** [comment]
Other thoughts: most packages use autoconf [citation needed, I assume so]: do they also get bug reports from alternate OSes?

**Comment by carandraug** [comment]
Why having a configure script at all in this case?  The only reason is to catch an incorrectly configured system during install and give a nice error message. If you can give the same helpful message during runtime, then there's little reason to have it.

If you can't (or you don't want to because it slows it down) and this is giving false positives, it is possible to:

* change the `AC_MSG_ERROR` to `AC_MSG_WARN`
* modify the checks so they match what the the package really does

Note that the configure script only means that the system is good during install. Nothing stops the user from changing python or sympy after install and break or fix it so maybe a warning would indeed be better.

> Other thoughts: most packages use autoconf [citation needed, I assume so]: do they also get bug reports from alternate OSes?

No, this is common at all. I actually think this has reduced the bug reports because there's less people reporting invalid bug about a missing mkoctfile.

**Comment by cbm755** [comment]
Ok, at least changing to warning sounds good...

There was also #236: which I'm not sure is fixed.  I forgot to report this, but during my limited testing on a windows box, it seemed to break if I "pinned-to-taskbar" and then closed and re-launched Octave that way: needs to be reconfirmed.

**Comment by mtmiller** [comment]
If you have a run-time check for Python, that seems as useful to me as the current configure script. The configure script only checks at the time of installing the package, but it's possible Python isn't installed at that time, or gets upgraded or moved later.

I'd vote for ditching the configure script, bring it back if you'd ever want to compile against something, or check for features in Octave and abort (or modify) installation if they are missing.

**Comment by cbm755** [comment]
Another data point: because Symbolic Pkg is going to have some `@double` implementations from the Specfun Pkg (#409, #398, https://savannah.gnu.org/patch/?8644), Python/SymPy should probably be optional dependencies.

**Comment by cbm755** [comment]
Ok, they are warnings for now.

Proper run-time error reporting might require some work.  Fairly easy for Python but `import sympy` is pretty much hardcoded into all our IPC stuff: maybe the error message for no SymPy is good enough...

**Comment by cbm755** [comment]
here's what I get at runtime if I have no sympy:
````
error: Python exception: ImportError: No module named sympy
    occurred in python_header import block
error: called from
    python_cmd at line 178 column 5
    sym at line 365 column 5
    syms at line 162 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 162 column 9
````

Cheap hack idea: we could display some extra message in whenever we get that particular error back in `python_cmd`.  Something more explicit like: `you need to install SymPy on this system`.

**Comment by mtmiller** [comment]
I get the same output, and the following when there is no `python` executable in `PATH`:

    error: popen2: popen2 (child): unable to start process -- No such file or directory
    error: called from
        python_ipc_popen2 at line 91 column 19
        python_ipc_driver at line 57 column 13
        python_cmd at line 166 column 9
        sym at line 365 column 5
        sym at line 236 column 7
        sym at line 211 column 7
    warning: readblock: s=-1, errno=4, perhaps error in the command?
    warning: called from
        readblock at line 94 column 7
        python_ipc_popen2 at line 116 column 14
        python_ipc_driver at line 57 column 13
        python_cmd at line 166 column 9
        sym at line 365 column 5
        sym at line 236 column 7
        sym at line 211 column 7

and that just repeats forever until I <kbd>Ctrl</kbd>+<kbd>C</kbd> (or maybe times out).

**Comment by cbm755** [comment]
Thanks Mike.  It repeats forever because we don't check anything before blindly calling it: that should be fairly easy to fix.  The IPC also expects rather specific output and can hang like that if it never gets it.

FTR: an easy way to make this happen is `sympref python meh` where I have no `meh` in my path.

**Comment by mtmiller** [comment]
Ping! Any thoughts on whether we can drop configure and the entire src subdirectory before the 2.5 release? One point brought up in #641 is that when a package has a src subdirectory, users need to have liboctave-dev installed on deb-based systems (the check for mkoctfile is mandatory when a src subdirectory is present). If we drop src, users can install and not need to install a pile of development libraries and compilers that they might otherwise not have installed already.

**Comment by cbm755** [comment]
OK, let's do it.

1.  `src/generate_functions.py` is not part of the install process, but it will have to move somewhere.  Maybe `util/generate_functions.py`?   Same for `src/Makefile`

**Comment by mtmiller** [comment]
👍 How about a `maint` subdirectory for tasks / scripts that are useful for the maintainer?

**Comment by carandraug** [comment]
> Maybe `util/generate_functions.py`? Same for `src/Makefile`

The current style in Octave Forge is to have such maintainer `Makefile` at the root of the package so instead of calling 'make_release_packages.sh' you would simply run `make release`. This would also has the advantage of working the same as the other package. Here's some examples:

* [image maintainer Makefile](http://hg.code.sf.net/p/octave/image/file/906cc54d9b9b/Makefile)
* [dicom maintainer Makefile](http://hg.code.sf.net/p/octave/dicom/file/5a7ee1735115/Makefile)
* [interval maintainer Makefile](http://hg.code.sf.net/p/octave/interval/file/a36bc6d9c503/Makefile)

for git repositories, there's only this one:

* [bsltl maintainer Makefile](https://sourceforge.net/p/octave/bsltl/ci/master/tree/Makefile)

**Comment by cbm755** [comment]
Thanks @carandraug for the reminder: we do have #254 to adopt the maintainers makefile, so for sure that could be dealt with at the same time as this current issue.

But it doesn't have to.  `generate_functions.py` is a development tool; it could be integrated into the maintainers makefile or not.

Matlab package generation stuff: certainly should be part of the maintainers makefile.

**Comment by cbm755** [comment]
So @mtmiller, I think I've changed my mind: let's *not* have a `maint` subdir.  Let's stick with `util/generate_functions.py`.  And our current `src/Makefile` would then become part of the maintainer Makefile...

**Comment by mtmiller** [comment]
LGTM.
