### ISSUE TITLE
Add `equationsToMatrix` command

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#576]
Someone asked on the maillist.  Looks like its:

https://www.mathworks.com/help/symbolic/equationstomatrix.html

**Comment by latot** [comment]
:O nice, i think i have an idea how do this!

**Comment by latot** [comment]
mm, to do this we need more info, for the moment my doubt its this:
```
syms x y
equationsToMatrix(x, y, y)  %%What are eqs and what are vars?
equationsToMatrix(x, y)  %%Same, i can suppose x is eqs and y vars.
equationsToMatrix(x)  %%What this should return?
```

**Comment by latot** [comment]
okis, that doubts was explained in the doc in matlab, so continues.

**Comment by cbm755** [comment]
This octave-help post http://lists.gnu.org/archive/html/help-octave/2016-09/msg00092.html provides includes an example.

**Comment by cbm755** [comment]
`sympy.solveset.linear_eq_to_matrix` is mentioned [here](https://groups.google.com/forum/#!topic/sympy/Wqs1OhTBexg), haven't tried it.

**Comment by latot** [comment]
:O lets check it, (i try search but i can't found D:)

**Comment by latot** [comment]
mmmmmmmmmmmmm, this seems very useful, don't is documented nowhere, but we can check the source directly: https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L989
The only problem with this is it don't detect non linear systems (this is for SMT compat), but if we check it manually like in the pr it would be more expensive call ```linear_eq_to_matrix```, because we can make the solution in the recursion of the check.

So the question is, keep that feature of SMT?

Only to be clear, this should send an error:
```
equationsToMatrix(x*x, x)
```

Thx.

**Comment by cbm755** [comment]
Oh, I'm sorry, I hadn't seen your PR when I sent that link.

I agree nonlinear equations should be an error.  It scares me if the sympy code does *not* check that...
