### ISSUE TITLE
fix euler number in sym (and probable other too)

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#591]
Missed symbols:

```
sym(e)
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
warning: called from
    sym at line 225 column 7
ans = (sym)

  1457
  ────
  536 
```

**Comment by latot** [comment]
from https://www.gnu.org/software/octave/doc/v4.0.1/Mathematical-Constants.html
seems e is the only left.

**Comment by cbm755** [comment]
We could do this, similar to our special treatment for pi...  My thoughts:

(+) It is of no concern for SMT compatibility b/c AFAIK `e` is not a command in Matlab (you have to say `exp(1)`).

(-) One downside is you cannot do `syms a b c d e` to get some vars...  I remember something similar that used to frustrate me in Maple, where `D` was a command.

(-) If we do this, why not make `sym(sqrt(2))` work, `sym(sqrt(2)/2)` etc.  Its kind of a slippery slope...

I'm undecided.  Why did you want this?  Just because Octave has `e` in the document you linked above?

**Comment by latot** [comment]
mm, i use a lot the number e, but when we work with octave we have written the scripts only with that letter, like ```e^x``` but when we convert the expressions to sym we found e its a symbol and its not detected like pi..
about ```sym(sqrt(2))``` i think sym shouldn't trate with that type of expressions, like only symbols, i only think this because the sym file fo this..
Octave vs SMT?

**Comment by mtmiller** [comment]
My first inclination would be to use

    e = exp (sym (1))

if I needed `e` as a constant.

I originally thought this would be a good idea to match `pi`, but since it's a single letter I agree with @cbm755 that it would be bad to make it hard-to-impossible for users to define a sequence of symbolic vars `a b c d e f g`.

**Comment by latot** [comment]
mm, okis, the only think i'm little worried is the octave doesn't have how to know this behavior.

**Comment by cbm755** [comment]
Perhaps the real issue here is that `sym(char)` should generally, in most cases, just make variables whereas `sym(double)` could have magic behaviour (like `sym(pi)`).  That seems closer to how SMT is these days.  I've filed #604.

If `syms e` could still make a variable called `e`, then I think I'm +1 for having `sym(e)` (and `e^x`) do the right thing...

**Comment by latot** [comment]
only for the record, if the decision is keep e as variable, maybe send a warning to say the difference?
```Warning: the e expression don't is the euler number.```

**Comment by latot** [comment]
Hi, other idea, if we enable ```e``` only in octave? with this we can keep compat with octave and SMT.

**Comment by cbm755** [comment]
I think I prefer having the same behaviour on Octave and Matlab.
