### ISSUE TITLE
error in octave, _compactformat_ undefined

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#713]
Hi all, seems the option ```__compactformat__``` was removed from octave:

```
octave:2> a=sym(1)
error: '__compactformat__' undefined near line 1 column 3
```

the problem is in the display file:
```
grep -r compactformat
inst/@sym/display.m:    loose = eval('! __compactformat__ ()');
```

at least seems only happen in this case.

Thx. Cya.

**Comment by cbm755** [comment]
what octave version is this?  attach a bit of `ver` output.  There were problems about this but I thought we'd worked it out...

**Comment by mtmiller** [comment]
In Octave's 4.3 development branch, both `get(0, 'FormatSpacing')` and `__compactformat__` have been dropped, there is currently no way to query whether the output format is in compact mode or not.

**Comment by mtmiller** [comment]
Open upstream issue: https://savannah.gnu.org/bugs/?46603

**Comment by latot** [comment]
Hi, Thx, for the doc!

**Comment by mtmiller** [comment]
This is fixed upstream,

http://hg.savannah.gnu.org/hgweb/octave/rev/f84aa17075d4

The new (pre-4.4) way to query the output format is with

    [fmt, spacing] = format ()
    fmt =
    
    short
    
    spacing =
    
    loose
    

Is this good enough to use here or should something better be done upstream?

There are a couple of shortcomings I see with this approach:

* `nargout('format')` doesn't work because it is a compiled function
* calling `[a,b] = format` in Octave 4.0, for example, will reset the format to defaults, and then error that the number of output arguments doesn't match

**Comment by cbm755** [comment]
Thanks everyone.  @mtmiller: I think that API will be fine for us.
