### ISSUE TITLE
[Octave 4.4.1/Windows 10] Not expected display

### ISSUE THREAD

**Issue by LapinFou** [cbm755/octsympy#912]
Hi Folks,

I'm new in the Octave world. I discovered this promising package.
I followed the windows installation (bundle one).
After fixing the **utf8_heavy.pl** warnings, it seems to be working fine. However, the displayed formula doesn't look at all like the snapshot on the website.
Here is what I got:
![tmp](https://user-images.githubusercontent.com/1685030/46360760-6babf800-c66c-11e8-8538-833f799a1d20.png)

What have I done wrong??

Thanks. 😄

**Comment by mtmiller** [comment]
Are you asking about the display of the output here:
![u](https://user-images.githubusercontent.com/244682/46363606-57460c00-c628-11e8-82a7-6ae75ea360ad.png)
versus what you are seeing here:
![a](https://user-images.githubusercontent.com/244682/46363628-6a58dc00-c628-11e8-850d-59a3ca04895f.png)
?

If so, then this is an intentional difference between the default behavior in Octave on Windows versus a GNU/Linux or Unix system.

It is a known problem under development that Unicode output does not work reliably in the command window in Octave for Windows. So this package sets the display to use ASCII formatting by default on Windows.

You can try `sympref display unicode` on Windows to see if it works for you.

See also #83.

**Comment by cbm755** [comment]
The utf-8 heavy warnings are harmless.  The next release of  Octave (or at least version 5.0) will fix that.

**Comment by LapinFou** [comment]
Thanks folks!
With your help, I got it working.
1- **sympref display unicode**
2- **DejaVu Mono Sans** must be selected as a font in the preference tab.

Then, now the display looks exactly as expected:
![tmp](https://user-images.githubusercontent.com/1685030/46402616-88920b00-c700-11e8-9a8c-c6df4df3c5b3.png)

I guess this ticket can be closed. However, It think it could be nice to add those information on the WiKi.

Seb

**Comment by cbm755** [comment]
Very nice, I didn't know this was possible.

I will leave this open until we get it documented somewhere.  Can you try to put these instructions, and your lovely screenshots, at https://wiki.octave.org/Symbolic_package

And/or we should link it from the 'notes on windows install' here on github.

**Comment by cbm755** [comment]
Note: I can't switch the default to Unicode until it works OOTB, without tweaking fonts.  Maybe upstream Octave GUI should default to the DejaVu font?

Did you install that font or did it ship with Octave?  Very unlikely MS ships a libre font with their OS...

**Comment by LapinFou** [comment]
I will try to create a PR for the screenshot.

Concerning the font, you're right it not ship with Octave nor with MS.
Steps to install the font on Win10 computer are easy:
1. Download the fonts from http://dejavu.sourceforge.net/
2. Go in the folder **dejavu-fonts-ttf-2.37\ttf**
3. Select the required font, then right click and choose "Install". You must have administrator rights.

**Comment by cbm755** [comment]
I just tested with the new Octave 5.1 and `sympref display unicode` seems to work out of the box using the default font ("Courier New").

<img width="600" alt="win10_oct51_unicode" src="https://user-images.githubusercontent.com/818622/53717899-7252bd00-3e0e-11e9-9faf-7b86a4aeeb1a.png">

Maybe we should default to unicode display on Win10...?

Note `help @sym/sym` is still broken

**Comment by LapinFou** [comment]
Still doesn't work for me.
Could you try this formula ?
`syms x y z a b c k`
 `A=[sin(x/2) floor(a^(x*c));acosh(2*x/pi) ceil(sin(x/gamma(x)))]`

**Comment by cbm755** [comment]
<img width="467" alt="Capture4" src="https://user-images.githubusercontent.com/818622/54062468-016b2680-41bb-11e9-8e19-e9131f15022e.PNG">

the alignment is messed up but the symbols look OK.

(Note the Unicode cross in `sym 2x2 matrix` is broken; I think this is because of `__mfile_encoding__`; I think that could be worked around by not including any raw utf8 in our m files.)

What do you see?

**Comment by LapinFou** [comment]
I got the same result as you. But with the font **DejaVu Mono Sans**, everything is OK.

**Comment by cbm755** [comment]
Ok thank you.

So out -of-the-box Octave 5 can (mostly) display our unicode output.  But while it is technically working, maybe its still not sufficiently high quality to enable by default.

Leaving this open b/c still todo: [document instructions from above](https://github.com/cbm755/octsympy/issues/912#issuecomment-426921008) on a wiki somewhere

**Comment by cbm755** [comment]
documented in wiki and linked here
