### ISSUE TITLE
rename `python_cmd`

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#986]
`python_cmd` is mostly an internal function.  Some people may find it useful but its also likely to generate confusion for [Pythonic](https://gitlab.com/mtmiller/octave-pythonic/): in fact it already has on a maillist.

  * Consider renaming it to something like `_python_cmd_`, although that probably breaks matlab...
  * it is mentioned in `INDEX` so should there be a deprecation cycle?  e.g., until 2.9.0 where the old name works but emits `warning`.

A counter argument is that some people may use it directly (to do something in sympy that we don't directly expose).

**Comment by mtmiller** [comment]
I think Matlab requires function names start with a letter, so something like `python_cmd__` should be ok. Should probably be tested for compatibility first.

Consider naming it something with `sympy` in the name since it implicitly pulls in sympy names in the header and handles input and output arguments?

Yeah, deleting the name entirely should bump the version to 3.0.0, could keep a deprecation wrapper until then.

**Comment by cbm755** [comment]
Good idea re: "sympy".  Maybe I like `pycall_sympy__`: we're calling a python function with sympy in the namespace.

Quick questions:
1. I assume the (old) wrapper `python_cmd` should stay in `INDEX` during the deprecation (?)
2. Should `pycall_sympy__` be listed in `INDEX` or not?  It lives in `inst/` but is essentially private (in principle).

**Comment by mtmiller** [comment]
IMHO the main purpose of INDEX is what functions do you want to be visible at https://octave.sourceforge.io/symbolic/overview.html

So I would keep `pycall_sympy__` out of INDEX, and keep `python_cmd` in INDEX for continuity until it's completely removed.
